// Generated by ActionCoffee 0.0.1

class Test {
 
public function Test(x) {
  this.x = x;
}

public function test() {
  return trace("This is a test.");
};

public function staticmethod() {
  return trace("static method");
};
 };
